config/routes.rb
Rails.application.routes.draw do
get  "/signup", to: "signup#new", as: "signup"
post "/signup", to: "signup#create"
# Sign in or sign out
get    "/login",  to: "login#new", as: "login"
post   "/login",  to: "login#create"
get "/logout", to: "login#destroy", as: "logout"
  root "articles#index"
  
  resources :articles do
    resources :comments
  end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_login
    unless current_user
      redirect_to login_path
       flash[:alert] = "You must be logged in to access this section."
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to root_path
    else
      flash.now[:alert] = "There were some errors while creating the article."
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to root_path
    else
      flash.now[:alert] = "There were some errors while updating the article."
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article was successfully deleted."
    redirect_to root_path, status: :see_other
  end
  
  def article_params
    params.expect(article: [:title, :body])
  end
  def comment_params
    params.expect(comment: [:commenter , :body])  
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:create]
 
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment was successfully created."
      redirect_to article_path(@article)
    end
  end
  #if i used @article.comments.create ... it would save directly without validation and without if @comment.save check
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

# #this below sits the article_id manually
# class CommentsController < ApplicationController
#   def create
#     @comment = Comment.new(comment_params)
#     @comment.article_id = params[:article_id]
#     if @comment.save
#       flash[:notice] = "Comment was successfully created."
#       redirect_to article_path(@comment.article)
#     end
#   end
#   private
#   def comment_params
#     params.require(:comment).permit(:commenter, :body)
#   end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Login successful!"
    else
      flash.now[:alert] = "Invalid email or password."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "Logged out successfully."
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path , notice: "Signup successful!"
    else
      flash.now[:alert] = "There were some errors during signup."
      render :new
    end
  end

  private

  def user_params
    params.expect(user: [:name, :email, :password, :password_confirmation])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": article.errors[:body].none?, "border-red-400 focus:outline-red-600": article.errors[:body].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.textarea :body, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": article.errors[:body].none?, "border-red-400 focus:outline-red-600": article.errors[:body].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit "publish" ,  class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="max-w-2xl mx-auto my-10 p-10 border border-gray-300 rounded-lg shadow-lg">
  <h1 class="text-3xl font-bold mb-5">New Article</h1>
  <%= render  "articles/form" , article: @article%>
</div>
<div class="max-w-2xl mx-auto my-10 p-10">
  <%= link_to "Back to Articles", articles_path, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
</div>

app/views/articles/index.html.erb
<% content_for :title , "All Articles"%>
    <div class="grid grid-cols-4 gap-10 m-4 mb-6 mx-w-auto">
       <% @articles.each do |article| %>
        <div class=" border-grey-300 py-5 px-10 rounded-lg shadow-lg bg-blue-100 text-center ">
        <div class=" grid mb-4">
        <p class="font-bold text-2xl text-sky-700"> <%= article.title %></p>
        </div>
        <div>
              <%= link_to "Read this article!", article, class: "mt-3 w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-500 hover:bg-blue-300 inline-block font-small text-white mb-3" %>
        </div>
        <p class="font-bold text-xl text-black"> written by <%= article.user.name %> </p>
      </div>

    <% end %>
  </div>

     <div  class="p-8 py-3 px-2 rounded-md mt-8 grid lg:grid-cols-2 gap-6 bg-gray-100 max-w-md mx-auto">
       <h2 class="text-lg font-semibold mb-6">Log into your Account!</h2>
       <%= link_to "Log in!", login_path, class: "inline-block px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-md mb-5" %>
       <h2 class="text-lg font-semibold mb-3">Want to register your own account?</h2>
       <%= link_to "Sign up!" , signup_path, class:"inline-block px-4 py-2 bg-green-600 hover:bg-green-500 text-white font-medium rounded-md mb-5"%>
     </div>
      

app/views/articles/new.html.erb
<div class="max-w-2xl mx-auto my-10 p-10 border border-gray-300 rounded-lg shadow-lg">
  <h1 class="text-3xl font-bold mb-5">New Article</h1>
  <%= render  "articles/form" , article: @article%>
</div>

app/views/articles/show.html.erb
<% content_for :title , "Your Note"%>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-6xl mt-10">

  <!-- LEFT SIDE -->
  <div class="space-y-8">

    <!-- Article -->
    <div class="p-10 border border-gray-300 rounded-lg shadow-lg bg-white">
      <h1 class="text-3xl font-bold mb-5"><%= @article.title %></h1>
      <h2 class="text-lg italic mb-5">written by <%= @article.user.name %></h2>
      <div class="border border-gray-200 mb-6">
        <p class="text-lg"><%= @article.body %></p>
      </div>
    </div>

    <!-- Add Comment Form -->
    <div class="p-10 border border-gray-300 rounded-lg shadow-lg bg-white">
      <h2 class="text-xl font-bold mb-4">Add a comment:</h2>

      <%= form_with model: [ @article, @article.comments.build ] do |form| %>
        <p class="mt-4">
          <%= form.label :body %><br>
          <%= form.text_area :body %>
        </p>

        <p class="mt-4">
          <%= form.submit "publish comment",  class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
        </p>
      <% end %>
    </div>

    <!-- Buttons -->
    <div class="flex space-x-4">
      <%= link_to "Back to Articles", articles_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-medium" %>
      <%= link_to "Edit this Article", edit_article_path(@article), class:"rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-medium"%>
    </div>

    <div>
      <%= button_to "Delete this Article", article_path(@article), method: :delete, class: "rounded-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white font-medium" %>
    </div>

  </div>

  <!-- RIGHT SIDE -->
  <div class="p-10 border border-gray-300 rounded-lg shadow-lg bg-white h-fit">
    <h2 class="text-2xl font-bold mb-5">Comments:</h2>

    <% @article.comments.each do |comment| %>
    <% next if comment.user.nil? %>
      <div class="mb-4 p-4 border border-gray-200 rounded">
        <p class="font-semibold"><%= comment.user.name %> says:</p>
        <p><%= comment.body %></p>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-stone-800 ">
    <main>
      <%= render "shared/nav_bar" %>
      <div class="pt-20">
      <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/login/new.html.erb
<% content_for :title, "User Login" %>
<div class="max-w-md mx-auto mt-10 p-6 bg-white rounded-md shadow-lg border-2 border-gray-400">
    <div>
     <% if flash[:alert] %>
       <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative  mx-auto my-4 text-center" role="alert">
         <span class="block sm:inline"><%= flash[:alert] %></span>
       </div>
     <% end %>
  </div>

  <h1 class="text-2xl font-bold mb-5 text-center">Login</h1>

  <%= form_with url: login_path, local: true do |f| %>
    <div class="mb-4">
      <%= f.label :email, class: "block font-medium mb-1" %>
      <%= f.email_field :email, class: "w-full border px-3 py-2 rounded-md", required: true %>
    </div>

    <div class="mb-6">
      <%= f.label :password, class: "block font-medium mb-1" %>
      <%= f.password_field :password, class: "w-full border px-3 py-2 rounded-md", required: true %>
    </div>

    <%= f.submit "Login", class: "w-full bg-green-600 hover:bg-green-500 text-white px-4 py-2 rounded-md font-medium" %>
  <% end %>

  <p class="mt-4 text-center text-sm">
    Don't have a registered account?    <%= link_to "Sign up", signup_path, class: "text-blue-600 hover:underline" %>
  </p>
</div>

app/views/shared/_nav_bar.html.erb

<nav class="bg-neutral-primary fixed w-full z-20 top-0 start-0 border-b border-default bg-opacity-60 backdrop-blur-md bg-zinc-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <span class="self-center text-4xl text-heading font-semibold whitespace-nowrap text-indigo-800">Articles</span>
    <button data-collapse-toggle="navbar-multi-level-dropdown" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-body rounded-base md:hidden hover:bg-neutral-secondary-soft hover:text-heading focus:outline-none focus:ring-2 focus:ring-neutral-tertiary" aria-controls="navbar-multi-level-dropdown" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M5 7h14M5 12h14M5 17h14"/></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-multi-level-dropdown">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-default rounded-base bg-neutral-secondary-soft md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-neutral-primary">
        <li>
            <%= link_to "Home", articles_path, class:"block py-2 px-3 text-white bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0" %>
        </li>
        <li>
            <%= link_to "write an article!" , new_article_path , class:"block py-2 px-3 text-white bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0" %>
        </li>
        <li>
          <%= link_to "Log in" , login_path , class:"block py-2 px-3 text-green-700 font-bold bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0" %>
        </li>
        <li>
          <%= link_to "Sign up" , signup_path , class:"block py-2 px-3 text-green-700 font-bold bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0" %>
        </li>
        <% if current_user %>
        <li>
          <p class="block py-2 px-3 text-white bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0 flex items-center"> You're logged in as <span class="block py-2 px-3 text-green-900 bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0 font-bold text-2xl font-serif"><%= current_user.name %></span> </p>
        </li>
        <li>
            <%= link_to "Log out", logout_path, method: :delete, class: "inline-block px-4 py-2 bg-red-600 hover:bg-red-500 text-white font-medium rounded-md" %>
        </li>
        <%else%>
        <li>
          <p class="block py-2 px-3 text-white bg-brand rounded md:bg-transparent md:text-fg-brand md:p-0 text-red"> You're currently not logged in </p>
        </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/signup/new.html.erb
<% content_for :title, "User Sign Up" %>
<div class="max-w-md mx-auto  p-6 bg-white rounded-md shadow-lg border-2 border-gray-300 mt-6">
  <% if flash[:alert] %>
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative max-w-2xl mx-auto my-4" role="alert">
              <span class="block sm:inline"><%= flash[:alert] %></span>
            </div>
          <% end %>
          
  <h1 class="text-2xl font-bold mb-5 text-center">Sign Up</h1>

  <%= form_with model: @user, url: signup_path, local: true do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: "block font-medium mb-1" %>
      <%= f.text_field :name, class: "w-full border px-3 py-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <%= f.label :email, class: "block font-medium mb-1" %>
      <%= f.email_field :email, class: "w-full border px-3 py-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <%= f.label :password, class: "block font-medium mb-1" %>
      <%= f.password_field :password, class: "w-full border px-3 py-2 rounded-md" %>
    </div>

    <div class="mb-6">
      <%= f.label :password_confirmation, class: "block font-medium mb-1" %>
      <%= f.password_field :password_confirmation, class: "w-full border px-3 py-2 rounded-md" %>
    </div>

    <%= f.submit "Sign Up", class: "w-full bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-md font-medium" %>
  <% end %>
</div>